### ISSUE TITLE
add ExcavatorNvidia

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.3#100]
"https://github.com/nicehash/excavator/releases/download/v1.3.8a/excavator_v1.3.8a_NVIDIA_Win64.zip"

**Comment by GillyTheGhillie2** [comment]
I did add Excavator to Nemos (modified versions of the MPM files) but it benched lower on all of its supported algorithms than CC-Alexis so I thought it redundant to continue using.

**Comment by nemosminer** [comment]
chur
