### ISSUE TITLE
ccminer-x64.exe -a cryptonight close directly on v2.3c-beta

### ISSUE THREAD

**Issue by yepla** [nemosminer/NemosMiner-v2.3#102]
Hello,
I have try the v2.3c-beta but there are a bug when mining cryptonight algo with ccminer-x64.exe
The miner start but close directly then start again and close ...
I m using NemosMiner-v2.3c-beta on miningpoolhub with a NVIDIA 950
So i need switch back to the v2.2.2 actually all the v2.3-beta has not work good for me hope a fix soon to be able to use it ...

**Comment by nemosminer** [comment]
this is made for 1060 1070 1070ti 1080 1080ti 

no 950 support sorry

**Comment by yepla** [comment]
could you tell me what i need to do to support 950 ? on the 2.2.2 it was working great !

**Comment by yepla** [comment]
I have remove -i 10 in Miners/CcminerTpruvotx64.ps1 and mining algo cryptonight with my NVIDIA 950 work !

**Comment by nemosminer** [comment]
thanks
