### ISSUE TITLE
Cryptonight + Eth won't work

### ISSUE THREAD

**Issue by Icehunter** [nemosminer/NemosMiner-v2.3#103]
Hi!

First off; awesome work!

I'm having an issue with 2.2.2.

1) If I set eth/ethash in the list of algo's eth is never used.
2) I can't mine crypto on my 1080ti because of the following message:

![image](https://user-images.githubusercontent.com/677341/34248553-68f4969c-e5eb-11e7-8f58-93f8a7e4fc71.png)

However with the mininghub 1.7.3 repo; it works just fine.

My system is as follows:
Xeon 3690
24 GB RAM
1080Ti
950 GTX
96GB of virtual memory set as a minimum.

Is there anything more I can provide to fix this?

Thanks!

**Comment by luxferro** [comment]
I also could never get ethash to work. I set it in the miningpoolhub .bat file, but it never benched it.

**Comment by nemosminer** [comment]
ethash is not enabled yet

**Comment by nemosminer** [comment]
im working on adding new miner for cryptonight

**Comment by Icehunter** [comment]
@nemosminer Thank you so much :) I assume that is why I get the out of memory exception? I also saw somewhere you are removing support for anything in the 9 series? So at that time I will just have to take the card out right?

**Comment by nemosminer** [comment]
its not that i don't support 9 series cards its just i only have 1060 and above cards so i can't test on the 9 series...
