### ISSUE TITLE
watch dog

### ISSUE THREAD

**Issue by gak45** [nemosminer/NemosMiner-v2.3#104]
Hi does nemosminer have a 'watch dog' type monitor to auto restart a failed miner like multipoolminer has? I ask as I do not see any option for such a feature and dont want to have to babysit my rigs 24/7.

**Comment by clownfish44** [comment]
It really needs one!

**Comment by nemosminer** [comment]
you should not have to babysit them... 

i run auto restart on all my rigs once every 24hours

if you cant get 24hours without a crash then something is wrong with your rig/risers/power/psu/pagefile..
