### ISSUE TITLE
DSTM on equihash.zpool.ca

### ISSUE THREAD

**Issue by pol0boy** [nemosminer/NemosMiner-v2.3#105]
I'm not a programmer i'm a miner using nvidia gpu. I tried the latest version of nemosminer 2.3 master and i'm encountring a problem when benchmarking equihash/zpool.ca : 

   Status : Failed

    Speed Active                      Launched Command
    ----- ------                      -------- -------
0,00 PH/s 00 Days 00 Hours 00 Minutes Once     Bin\NVIDIA-DSTM\zm.exe --telemetry=127.0.0.1:2222 --server
                                               equihash.mine.zpool.ca --port 2142 --user
                                               XXXxxxXXXXxxxXXXxxxXXxx --pass ID=NemosMiner-v2.3,c=btc -d
                                               0 1

**Comment by nemosminer** [comment]
which card/s are you using how many 
need more info if you want me to help you
screen shot?

**Comment by pol0boy** [comment]
Hin thanks for responding 
i'm using gtx 1070 2 cards

**Comment by nemosminer** [comment]
are you running 2.3 master or 2.3c-beta latest release?

can you take a screen shot of the DSTM console please so i can see whats happening 
which version of windows are you running?

Have you Followed all the Instructions on Page 1 of bitcointalk thread?

**Comment by pol0boy** [comment]
Good morning 
Sorry for the delay I'm using the latest version of nemosminer ( master version ) on windows 10 x64 ( 1709 ) and the DSTM console doesn't launch.
Yes, I followed all the instructions on the page.
Thank you =)

**Comment by nemosminer** [comment]
thankyou

**Comment by snxraven** [comment]
Hello, I have fixed this issue I have had by editing DSTM.ps1 in the Miners folder. 
[DSTM.ps1.txt](https://github.com/nemosminer/NemosMiner-v2.3/files/1592637/DSTM.ps1.txt)

Above is the version that got me going, for some reason it thought I had 2 cards when I only had one.
