### ISSUE TITLE
CCminer not loading...

### ISSUE THREAD

**Issue by iakram2000** [nemosminer/NemosMiner-v2.3#106]
So at first it ran a few algos then it got stuck at cryptonight
any help would be appreciated!
![image](https://user-images.githubusercontent.com/34780260/34313076-5d62399c-e771-11e7-96fe-a418d8fc87a4.png)

**Comment by nemosminer** [comment]
tested on 1060 1070 1070ti 1080 1080ti....   no 750ti support

You are using a 750ti.. disable cryptonight from -algos
