### ISSUE TITLE
BTC/Day

### ISSUE THREAD

**Issue by mctrivia** [nemosminer/NemosMiner-v2.3#107]
Well I wish this was true but it says Lyra2z I will make 2.3BTC/day

Using 1060 3GB card.
V2.3c

**Comment by mctrivia** [comment]
Figured out.  Miner giving error misaligned address or unspecified launch error and fake hashing at a few ghs.

**Comment by nemosminer** [comment]
thanks can you send me screen shot please

**Comment by mctrivia** [comment]
![error](https://user-images.githubusercontent.com/14829699/34382498-f66ea6fa-ead4-11e7-9f81-9627a862ec11.png)

**Comment by sainandan5173** [comment]
yes there is some problem benchmarks and profit switchin is not as per mining pool hub

**Comment by nemosminer** [comment]
added --submit-stale to lyra2z tested working on miningpool hub
