### ISSUE TITLE
NeoScrypt not completing benchmark

### ISSUE THREAD

**Issue by tonyharney** [nemosminer/NemosMiner-v2.3#108]
All algorithms complete benchmark except for NeoScrypt.  The benchmark loops for about 12 minutes and saves the hash rate file as 0.

I'm using Windows 10 with a GTX 1070 and have ensured that I gave the most recent dll files up to date.

**Comment by GillyTheGhillie2** [comment]
I'd recommend sticking to releases rather than downloading potentially non-functional code.

**Comment by tonyharney** [comment]
I downloaded the master branch, not the beta one.  Is there a different version of Nemos Miner I should be downloading?

**Comment by tonyharney** [comment]
The following allowed for NeoScrypt to benchmark:

modify CcminerKlaust.ps1
"neoscrypt" = " -i 15 -d $SelGPUCC" #NeoScrypt

**Comment by GillyTheGhillie2** [comment]
Yes, you should be downloading the releases.

**Comment by tonyharney** [comment]
Not to be rude, but why is the response to an issue to not use this version?  Isn't the whole point of this issues thread to help find issues with the current release of software?

**Comment by nemosminer** [comment]
use the latest release you should have no promblems...  : https://github.com/nemosminer/NemosMiner-v2.3/releases/download/NemosMiner-v2.3c-beta/NemosMiner-v2.3c-beta.zip 

the master is the most up to date code that is not complete nor thoroughly tested so i would not suggest using it i should find that issue my self when i run it through test rigs before my next release

**Comment by GillyTheGhillie2** [comment]
You aren't using a release, you are using the main branch...
