### ISSUE TITLE
Benchmark does not measure accurately depending on the algo.

### ISSUE THREAD

**Issue by Parask82** [nemosminer/NemosMiner-v2.3#112]
CCMinerAlexis78, maybe other CCMiner versions also, average hashrate from the last 30 shares submitted by default so on algos that take a lot of seconds per share it does not have enough time to reach closer to real hashrate produced by the system. So the end calculation about optimal profit are skewed in favor of algos that produce more shares per minute. Adding the parameter --statsavg and setting it to 5 or 10 should make this issue a lot better.

-edit typos

**Comment by nemosminer** [comment]
on your 1st run/benchmark edit start.bat change -interval 120  to  -interval 600  save and run benchmark it will take a long time but will be accurate after that you can edit start.bat again and chande -interval back to 120... 

Best Regards
Nemo

**Comment by nemosminer** [comment]
thankyou

**Comment by Parask82** [comment]
Thanks for the quick solution :)
