### ISSUE TITLE
Second Worker Doesn't Ever Show on MPH

### ISSUE THREAD

**Issue by twthereddragon** [nemosminer/NemosMiner-v2.3#113]
Hi, using NemosMiner-v2.3 with Miningpoolhub.  I have 2 different PC's with 2 nvidia cards each in them.  My first rig I setup fine with no issues & called it Main1.  It shows under my workers & it shows on miningpoolhubstats.

I set my 2nd machine as Main 2.  But it never shows.  I let it run overnight just thinking it might be a long delay, but it still isn't there.  Triple checked all of the settings and made sure username & workername were set correctly.  I've also seen a couple of posts on reddit & bitcointalk.org with people experiencing the same issue.  Any way to resolve this?  If I use AM or MPM then the 2nd machine shows up fine, but would rather both run Nemos.

**Comment by nemosminer** [comment]
ok i'll look into that thanks
