### ISSUE TITLE
Issue with first run

### ISSUE THREAD

**Issue by clownfish44** [nemosminer/NemosMiner-v2.3#114]
https://gyazo.com/296aabb7b95d43d14542ccd5764af7d3

How do i fix this so it runs

**Comment by nemosminer** [comment]
stop using the master code and use the latest release will fix that...

https://github.com/nemosminer/NemosMiner-v2.3/releases/download/NemosMiner-v2.3c-beta/NemosMiner-v2.3c-beta.zip
