### ISSUE TITLE
new Xevan ccminer

### ISSUE THREAD

**Issue by bykka** [nemosminer/NemosMiner-v2.3#115]
There is another xevan ccminer https://github.com/krnlx/ccminer-xevan/releases/download/0.1/ccminer_x86.exe

For my overclocked GTX 1070 TI works much better.
Current CcminerAlexis78cuda9 always stopped with error "Illegal memory access".

**Comment by nemosminer** [comment]
nope CcminerAlexis78cuda9 is faster i don't get that problem i have a 6x1070ti rig running xevan right now..

**Comment by bykka** [comment]
You are right. My bad.
