### ISSUE TITLE
Neoscript out of memory

### ISSUE THREAD

**Issue by bykka** [nemosminer/NemosMiner-v2.3#116]
CcminerKlaust throw out of memory for algorithm neoscrypt (4 videocards GTX1070TI)

```
[2017-12-25 20:22:28] neoscrypt.mine.ahashpool.com:4233 neoscrypt block 45319
Cuda error in func 'neoscrypt_cpu_init_2stream' at line 1433 : out of memory.
```
but NVIDIA-TPruvotcuda9 works fine

**Comment by GillyTheGhillie2** [comment]
This is a CC-Klaust problem, nothing to do with Nemos.

**Comment by bykka** [comment]
I understand that. But if this issue will be reproducible and for other guys than Nemos can change settings for miners.

**Comment by nemosminer** [comment]
i have tested CcminerKlaust with 1070ti it much faster than NVIDIA-TPruvotcuda9

for me and all my test rigs 1060's 1070's 1070ti's 1080ti's NVIDIA-CcminerKlaust works fine....

**Comment by bykka** [comment]
As I've mentioned above I have 4 GTX1070TI. NVIDIA-CcminerKlaust works fine for each or for three of them but not for four. I understand it is not a Nemos issue. Just wanted to inform.

**Comment by nemosminer** [comment]
thankyou
