### ISSUE TITLE
DSTM doesnt launch and cuda error

### ISSUE THREAD

**Issue by heliaoo** [nemosminer/NemosMiner-v2.3#121]
Hi guys, first time using nemosminer, i got 2 issues

1 - when benchmarking DSTM doesn't launch

2 - the img below
![miner error](https://user-images.githubusercontent.com/24615839/34362462-e55e88b4-ea5a-11e7-8747-6e7c7d299b01.PNG)

im using win 10 pro 64, 1060 6gb (diver version 388)  with stock settings for now, i already tried to use 3c beta and master, same problem.

for now i delete all algo that uses this miner

no problem with those
![runing miner](https://user-images.githubusercontent.com/24615839/34362842-12ec6348-ea5e-11e7-9020-33fde9100977.PNG)

Anyway, thx guys!

**Comment by FyR0z** [comment]
Same problem here for one of my friend

**Comment by clownfish44** [comment]
Same issue with  when benchmarking DSTM doesn't launch

**Comment by clownfish44** [comment]
Just solved this issue by fixing my overclock. It was too high and unstable. Check yours out.

**Comment by heliaoo** [comment]
thx for the reply but no oc in my settings =/

**Comment by heliaoo** [comment]
its working for me now, dont know if its the best solution but here is what i did

download this miner https://github.com/nemosminer/ccminer-Alexis78/releases

replace the miner and the dll in Bin\NVIDIA-Alexis78 and rename the .exe to ccminer-alexis

hope it helps ;)
