### ISSUE TITLE
watchdog for ccminer

### ISSUE THREAD

**Issue by Bizzaro** [nemosminer/NemosMiner-v2.3#122]
Is there a watchdog in place?  

Right now I'm using a hacked together script that checks GPU utilization with nvidia-smi and reboots the whole rig when it's been underutilized. I rather not do this long-term...

Trying to find the root cause of the reboots, but some of them seem to be from ccminer crashing... 
Is there a ccminer log somewhere?

<img src=https://i.imgur.com/FJVB0LZ.jpg>

**Comment by TomaszDom** [comment]
Can you share your script here? I'm facing the same issue, there has to be a more elegant solution using ccminer's API, which is unfortunately disabled by default on nemosminer, as such there is no way for nemos to tell what's happening, it just sits there happily not mining at all.

**Comment by nemosminer** [comment]
yeh you should not be having crashes at all none.. i have 9 different rigs that never crash they all restart once every 24hours.. but never crash during there 24hour run...

id suggest checking your rigs ... risers,psu,power,overclocking api for ccminer is now supported to...
