### ISSUE TITLE
Neoscrypt not benchmarkable

### ISSUE THREAD

**Issue by jagauthier** [nemosminer/NemosMiner-v2.3#126]
It appears that KlausT's ccminer doesn't support api-remote, so it's not being benchmarked.

[2017-12-27 14:42:09] NVML GPU monitoring enabled.
unknown option -- api-remote
Try `ccminer --help' for more information.

**Comment by nemosminer** [comment]
fixed

**Comment by kevharper** [comment]
I had this same issues a while back.  How to up update my Nemo's Miner to get the latest code for this fix?

**Comment by kevharper** [comment]
I downloaded the new .ps1 file, replaced the old one with it, cleared my status and benchmark data.  I see this message when I restart NemosMiner.  

![image](https://user-images.githubusercontent.com/34816613/34469502-741f1fc2-eeee-11e7-9f57-a1c4e1ce194c.png)

**Comment by kevharper** [comment]
After downloading the complete package (not just the new .ps1 file) , it appears  to be acting normally - working through the benchmarks now.  I will provide feedback with benchmarking is complete.

**Comment by jjude80** [comment]
just a note, make sure your nvidia drivers are up to date, so they support cuda 9.1
