### ISSUE TITLE
Neoscrypt Crashes While Mining

### ISSUE THREAD

**Issue by clownfish44** [nemosminer/NemosMiner-v2.3#127]
Status shows failed. Is there a log file for this or something which could solve my issue?
![jpeg_20171228_112936](https://user-images.githubusercontent.com/15145228/34417598-5ea5c9a4-ebc7-11e7-97ca-879c2f3f4c2c.jpg)

**Comment by nemosminer** [comment]
is this 2.3c-beta (latest release?) its seems to have completed benchmarks as it showing it speed and profitability as 2nd after skein atm...  is this (2x 1070 ?) 

try resetprofit.bat and resetbenchmark.bat

and re run

**Comment by clownfish44** [comment]
I re ran this and after many hours overnight it crashed. I am on two 1070's with no other issues and a very conservative oc. Is there a log file for this? Also why not add a watchdog that way it just relauches?
