### ISSUE TITLE
Show version of miners 

### ISSUE THREAD

**Issue by bykka** [nemosminer/NemosMiner-v2.3#128]
Is it possible to put a version of miners to directory name?
For example:
right now I have a miner Bin\NVIDIA-Alexis78
is it possible to rename it to something like Bin\NVIDIA-Alexis78-1.5.3?
or to add a comment about a version of a miner in the file Miners\ccminerAlexis78.ps1?

**Comment by nemosminer** [comment]
sure

**Comment by thericeking** [comment]
But does he have to add tge comment or not? I'm also interested in this question. Thank you
