### ISSUE TITLE
Interval is also Benchmark time?

### ISSUE THREAD

**Issue by dangi12012** [nemosminer/NemosMiner-v2.3#131]
I set the interval time to 3600 and cleared benchmarks. 45 minutes later I came back to see that no benchmark has been completed. Also can you confirm if -Interval 120 is in seconds? 

Can you implement a way to seperate benchmark time and interval?

**Comment by mahpoul22** [comment]
@dangi12012 -Interval is indeed in seconds, just set it to 120 for the benchmark and change it to 3600 once benchmark is done.

**Comment by kevharper** [comment]
What is the advantage of the larger interval after benchmarking is complete?

**Comment by mahpoul22** [comment]
@kevharper A bit more money for you if the pool you're mining with use the PPLNS payout method.

This is a very basic explanation and maybe not the right one to explain this.

**Comment by dangi12012** [comment]
Yes its really confusing BECAUSE: -Donate is in minutes. So -Donate 2 and -Interval 120 is the same time :S

**Comment by kevharper** [comment]
Speaking of donations.  Are they really  optional?
