### ISSUE TITLE
Ethash support

### ISSUE THREAD

**Issue by mmitech** [nemosminer/NemosMiner-v2.3#132]
is ethash going to be supported soon?

**Comment by mahpoul22** [comment]
@nemosminer yeah please man.

**Comment by thericeking** [comment]
Wait what? This doesn't support Ethash? I was about to move from MPM top this. Sadly I'm out back to MPM :(

**Comment by nemosminer** [comment]
i'll try get it in next release 2.3.1

**Comment by thericeking** [comment]
@nemosminer I see Ethash listed here https://github.com/nemosminer/NemosMiner-v2.3/blob/master/Algorithms.txt

Is it safe to download the master and start using it?
