### ISSUE TITLE
Watchdog implementation?

### ISSUE THREAD

**Issue by dangi12012** [nemosminer/NemosMiner-v2.3#134]
Are there any plans to implement rudimentary watchdog? Maybe via -Watchdog <Email Credentials>.
You could poll stdout for "does not validate" or a threshold hashrate (Maybe 75% of benchmarked value).

If that is implemented I would be happy to donate 0.15btc to your wallet!

**Comment by TomaszDom** [comment]
FWIW, I've mplemented a custom watchdog for my rig using tplink's hs110 wifi smartplug - it reboots the system when the reported power usage goes down below a certain threshold for longer than the defined number of minutes, it also pushes messages to my phone via IFTTT and is resiliant against reboot loops in case of Internet problems (it will only reboot once if that ever happens). 

It's a quick an dirty modification of https://github.com/robertvorthman/smart-plug-power-monitor but it works fine.

**Comment by dangi12012** [comment]
Cool I also have hs110. Didnt know that you can use them outside of Kasa app. How did you get the 10 minute threshold? In IFTTT Kasa is not a service to read from (So IFTT does not have power reading)

**Comment by TomaszDom** [comment]
dagni1202 if you really want to pay 0.15BTC then leave your email address here, I'll try to help you in private.

**Comment by dangi12012** [comment]
You are not one of the official contributors, so no.

**Comment by TomaszDom** [comment]
My hs110 watchdog is universal and has nothing to do with nemos or any other miner, but whatever.

**Comment by kevharper** [comment]
Does the HS110 watchdog require the 'Energy Monitoring' version of the HS110 or will the standard version work?

![image](https://user-images.githubusercontent.com/34816613/34549538-5a6fc654-f0d7-11e7-9868-cf0e98fe268c.png)

**Comment by nemosminer** [comment]
@dangi12012 im going to add watchdog support soon... thanks you don't need to pay me 0.15btc thanks for offer tho

**Comment by TomaszDom** [comment]
@kevharper yes you need energy monitoring for the watchdog to work.

It works quite simply, once you reach a programmed threshold (e.g. over 250W) watchdog sees this as "mining started". It then monitors the energy every 30 seconds. If power usage goes below the threshold (miner crashed), watchdog starts its programmed countdown (e.g. 10 minutes - gives it a chance to e.g. re-connect to the pool if you have serious connectivity problems or if you're just re-configuring your miners and forgot to disable the watchdog). If 10 minutes goes by and the power usage is still below the programmed threshold, watchdog reaches "mining crashed" action and cleanly reboots Windows. If watchdog rebooted the system as a result of connectivity issues and Internet or the pool still doesn't work after the reboot, then you won't reach the threshold for the watchdog to start again, so it won't endlessly reboot loop.
