### ISSUE TITLE
Won't Run .ps1 File as Admin

### ISSUE THREAD

**Issue by hbhodl** [nemosminer/NemosMiner-v2.3#135]
Hello,

I am getting this error when running the miningpoolhub batch file.

: The term '.\NemosMiner-v2.3.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the
path is correct and try again.

Doing some research some people said it had to do with running the program as an admin. I can get it to run not as admin but does anyone know how to edit the batch file so it will start as an admin?

Thanks for all the hard work!

**Comment by Klexicon** [comment]
Right click the .bat file and create a shortcut.  Right click on the shortcut ->Properties->Shortcut tab -> Advanced and click Run as administrator. Execute it from the shortcut.
