### ISSUE TITLE
Question/Request Excavator

### ISSUE THREAD

**Issue by thericeking** [nemosminer/NemosMiner-v2.3#138]
Hi and thank you for your hard work.

1. Can I use Excavator with NemosMiner? 

2. Any reason why not use Excavator with this miner?

I love how much simpler and clean your miner is and specially that is optimized for Nvidia miners like my self. I am currently donating 5 minutes on each f my mining rigs.

**Comment by nemosminer** [comment]
yeh there is no need excavator is slower hashing on all algos it supports compared to my current miners

**Comment by thericeking** [comment]
@nemosminer 
1.Does your miner support every single coin available for mining at MiningPoolHub? 
2. Can I also do CPU mining?

Thank you

**Comment by geckah** [comment]
Would it be too much trouble for you to release an excavator miner file? The recent updates have made it very competitive.

Thanks!
