### ISSUE TITLE
Question:  MPH - Setting Constant Difficulty for Skein

### ISSUE THREAD

**Issue by kevharper** [nemosminer/NemosMiner-v2.3#143]
I have been loving Nemosminer!  Awesome piece of code for us nVidia lovers!!

One issue I have with MPH is that the variable difficult on Skein is causing me to sometimes get emails that my miner is down when it really is not  (I believe because the difficulty varies to something too high for a result in under 10 min).   Is there a way in Nemosminer to set a constant difficulty for Skein?   Below is what is on the MPH site but I don't know how to implement it using Nemo.

Thank you!

![image](https://user-images.githubusercontent.com/34816613/34563411-8771968e-f120-11e7-9342-de9aaef159c2.png)

**Comment by jjude80** [comment]
just edit the ccminerAlexis78.ps1 file. Find "skein" = " -d $SelGPUCC --api-remote" #Skein and change it
'"skein" = " ,d=difficulty_level_here -d $SelGPUCC --api-remote"'

dont forget the comma before the d=

**Comment by jagauthier** [comment]
This change will be overwritten when you git pull updates.

**Comment by kevharper** [comment]
Thank you!  Any recommendation on how to pick a reasonable difficulty that is not too low?
