### ISSUE TITLE
Choose Coin in algo is important ?

### ISSUE THREAD

**Issue by Nateck** [nemosminer/NemosMiner-v2.3#144]
I can see on zpool on algo for example "blake2s" 3 different coins : Verge(XVG), Neva(NEVA), Taj(TAJ) and can observe that "Current Estimate" in table/stats info is the highest value between all coins in algo. When our NemoMiner is choosing the best algo, should also need use to mine the best profiting coin? So, if we have option in ccminer set "c=BTC", I think that then miner choose random coin and could mining low-profitable coin. Is my meaning correct? Can someone explain me how its works ?

**Comment by tooviral** [comment]
I believe zpool, hashrefinery, and ahashpool choose the best coin automatically for us.

**Comment by Nateck** [comment]
Look what they have on website:
„YOU MUST ALWAYS set your currency in your password field that matches your wallet address: c=<SYMBOL>. The pool has mined hundreds of different coins and many have the same address version. We CAN NOT read your mind and possible know what currency you want. If no c=<SYMBOL> is set, your currency will be randomly chosen from any matching coins we have used. This HAS TO BE A REAL EXCHANGE SYMBOL. Do not use a symbol that has an <ALGO> added. Such as XVG-blake2s or AUR-sha or DGB-skein, these are ALL WRONG. These are used only for the pool to support multi-algo coins.”

**Comment by russellt83** [comment]
c=BTC is for payout.
I'm certain that the pools automatically select which coin to mine.
