### ISSUE TITLE
Switch of the miners often is freezing.

### ISSUE THREAD

**Issue by D-TAU** [nemosminer/NemosMiner-v2.3#145]
Step to reproduce:
1. Run startzpool.bat
2. Wait for benchmarking.
3. Close  NemosMiner and start startzpool.bat again.
Over time switch of the miners are freezing. If select (focus) main NemosMiner window and press any key then miners will be switched.
This issue reproduces on the v2.3, 2.2 works well.

**Comment by jagauthier** [comment]
This is normal behavior when you use the mouse in a Windows command window.  Including just clicking in the body.  If you want to change focus, select the title.

Want proof?  Open a cmd prompt, cd to C:\ and run `dir /S`. Click in the window, highlight, etc..

**Comment by D-TAU** [comment]
This is not normal behavior because NemosMiner is freezing without manual control.
