### ISSUE TITLE
program on 8-card rigs, fix

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.3#146]
A friend of mine (who told me about this project) has a problem:
when running program on 8-card rigs, sometimes when mining program is to be switched , Nemo is killing the current miner - he gets "driver failed "error and then 1 of cards disappears
Any idea what might be the cause and cure?
[/quote]
I confirmed same fenomena - gracefully closing Alexis miner to driver crash and the card running main display disappears :(, need to restart
Even when making it manually with mouse :)
a possible workaround:
[code] $_.Active += (Get-Date)-$_.Process.StartTime
                $_.Process.CloseMainWindow() | Out-Null
                Sleep 1
                # if miner starts from Schedler, CloseMainWindow() is now enought, we have to force stop process by Id
                Stop-Process $_.Process | Out-Null[/code]
to
[code]
 $_.Active += (Get-Date)-$_.Process.StartTime
               # simply "Kill with power"
                Stop-Process $_.Process | Out-Null
                Sleep 2
[/code]

**Comment by chavvdarrr** [comment]
It seems it has to be forced, otherwise there will be question on cmd line
Stop-Process $_.Process -Force | Out-Null
I actually used the -Force when trying fix, but omitted it when writing in the forum
All the best

**Comment by nemosminer** [comment]
thankyou

**Comment by jimmykl** [comment]
can i confirm the code i have is:

```            
$_.Active += (Get-Date)-$_.Process.StartTime
                $_.Process.CloseMainWindow() | Out-Null
                Sleep 1
                # if miner starts from Schedler, CloseMainWindow() is now enought, we have to force stop process by Id
                Stop-Process $_.Process | Out-Null
                Write-Host -ForegroundColor Yellow "closing current miner and switching"
                Sleep 1
                $_.Status = "Idle"
            }```
and i should change that to
```           
 $.Active += (Get-Date)-$.Process.StartTime
              # simply "Kill with power"
               Stop-Process $_.Process | Out-Null
               Sleep 2
                $_.Status = "Idle"
            }

**Comment by nemosminer** [comment]
thanks added
