### ISSUE TITLE
I think the best version is v2.2 

### ISSUE THREAD

**Issue by chilak1l** [nemosminer/NemosMiner-v2.3#147]
all new updates are nice but the best real version makes me more profit is the release 2.2 you sould follow this version only make it better all versions beta i test it is not getting profit i using ahashpool its my fab pool well what you all guys think ?
I have 2 GTX 1080 and 5 GTX 1070.
  
I dont know why people mine on nicehash they take all your power for less ahashpool make a good profit I can't believe it

**Comment by nemosminer** [comment]
why are you finding v2.2 better?  Profitability wise? 
v2,2 and 2.3c-beta are basically the same if you run startahashpool.bat...

**Comment by JhonJhonny** [comment]
Actually i found the 2.3 more stable in general, and more profitable (by a
little tbh).
The only Think missing imho is a watchdog

Il 06 Gen 2018 11:22, "nemosminer" <notifications@github.com> ha scritto:

**Comment by nemosminer** [comment]
2.3.1 is not far away will have : 

Palgins HSR Neoscrypt 
XMRig Cryptonight

watchdog will be in next version 2.3.2...

**Comment by JhonJhonny** [comment]
Glad to hear it, any ETA for these to updates?
Will be upgradeable from the 2.3 or will be a fresh start?

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner-v2.3/tree/2.3.1+Palgin

**Comment by JhonJhonny** [comment]
Got to go so fast xD
Any ETA FOR the 2.3.2 then?

**Comment by chilak1l** [comment]
well its weird to tell but what I see is that 2.2 changes algorithms faster than the other version and let shares % on when a block find

**Comment by nemosminer** [comment]
ok......
