### ISSUE TITLE
Backup / failover pool

### ISSUE THREAD

**Issue by Coinminer24** [nemosminer/NemosMiner-v2.3#149]
Hi Nemo, any way to have a backup pool if main one goes down?

**Comment by nemosminer** [comment]
yes  i will be adding a new start.bat to 2.3.1 which will mine on all pools at once so if one goes down it will just skip to next profitable pool 

if you would like to try it edit the start.bat find -poolname zpool    change it to   -poolname zpool,ahashpool

**Comment by Coinminer24** [comment]
Thank you, will try it. How does it work if my primary is zpool and then I also add MPH given MPH needs username etc? Will it switch back to primary pool if it comes back up? I want to set zpool as primary and MPH as backup

**Comment by nemosminer** [comment]
yes you can have mph and zpool i will have to make a new start.bat that has username and btc address so it will work with zpool and mph i will be adding it to next version release

**Comment by airwalker1** [comment]
That will only work when the pool's api is down. I have seen this frequently where the api is up but something is causing stratum interruptions. Can you add a check based on the miner's api if it isn't hashing at X pool to go to Y for a time period?

**Comment by Coinminer24** [comment]
That would be fantastic if possible, this was the exact problem I was having with zpool. API up but pool down so miners sitting there doing nothing.

**Comment by Teqqles** [comment]
I was actually thinking a little broader as some pools have more profitable algorithms at a given time would it be possible to benchmark each and switch to a particular site given the margin you make. I know a few of us have access to zpool, mph and amining for example.
