### ISSUE TITLE
payment in a different currency

### ISSUE THREAD

**Issue by lipedoguaruja** [nemosminer/NemosMiner-v2.3#151]
I have a problem, I put the BTC wallet but it appears that I will be paid in BCH. Why is this happening?
![carteira 2](https://user-images.githubusercontent.com/35197769/34651821-dc511dfc-f3bc-11e7-8fed-348b46544c78.jpg)
![carteira](https://user-images.githubusercontent.com/35197769/34651822-dc8180d2-f3bc-11e7-9395-04ec5d241e7a.jpg)

**Comment by jagauthier** [comment]
Let's see the batch file you're starting the miner with.

**Comment by lipedoguaruja** [comment]
powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\NemosMiner-v2.3.ps1 -SelGPUDSTM '0' -SelGPUCC '0' -Currency USD -Passwordcurrency BTC -interval 600 -Wallet 1EBq4F4eBiHcqUxKMfGUBX2KM1MEbwKuLc -Location US -PoolName zpool -WorkerName ID=NemosMiner-v2.3 -Type nvidia -Algorithm poly,hsr,keccak,xevan,veltor,skunk,tribus,c11,x11evo,lbry,phi,skein,equihash,groestl,timetravel,sib,bitcore,x17,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,blake2s -Donate 5

**Comment by jagauthier** [comment]
When mining, what does the website site you are mining as?
![image](https://user-images.githubusercontent.com/7101432/34668584-0f9f3f16-f43c-11e7-923a-a874d093b0a1.png)
