### ISSUE TITLE
Suggest some tuning

### ISSUE THREAD

**Issue by ykuzmenko73** [nemosminer/NemosMiner-v2.3#152]
Hello
I would like to suggest some tuning to your greate miner
If you like them, add they to master if you want.

1) I made fixed first-time run of miner for 120 sec because we don't want skew miner's hashrate (it requires at least 2 minutes to become more-less stable)

2) I reduced the interval down to 30 sec because we are safe now to reduce it even lower because of (1)

3) I changed margin-of-error to be fixed because knowledge from the past don't let us to predict future so we can't be sure that past high fluctuation allow us to ignore one of the algo now

4) I introduced defencive 5% gain for current active algo because 5% is not too much but it prevent annoyng switching back and forth

I think this optimization can significantly increase the productivity of the farm because the miner will have reliable hash rate stats, it will react quite fast when new best algo appears and will not stuck for 2 minutes more with the previous best one that is far from the best now.

I have changed the outputs to be more informative also.

If you like the optimization, and if you willing to reward me, feel free to sent it to the BTC addres 
1KfYHBS7iYgf3QZRneWQVVDjR8Y2xtFC65

[NemosMiner-v2.2.1.zip](https://github.com/nemosminer/NemosMiner-v2.3/files/1612430/NemosMiner-v2.2.1.zip)

**Comment by Teqqles** [comment]
Would be better to have these as configurations via a pull request rather than a suspicious attachment

**Comment by airwalker1** [comment]
Agreed. Why are you using 2.21? Why not include these modifications to the latest nemosminer with palgin support?

**Comment by ykuzmenko73** [comment]
done, see PR https://github.com/nemosminer/NemosMiner-v2.3/pull/156
