### ISSUE TITLE
Miner closes and restarts on same algo and same pool

### ISSUE THREAD

**Issue by airwalker1** [nemosminer/NemosMiner-v2.3#154]
I cannot figure out why this occurs, but it's does so often and drives me nuts. Just as the title says I could be plugging away at one algo, the miner will close and restart on the same algo. It's as if the price change tells it to switch, even though its still at the top.

**Comment by airwalker1** [comment]
It appears Yuriy Kuzmenko has come up with a solution for this on commit 43bbf6a13fe03126de5fd5e60e731d86d66cc263

Thanks!

**Comment by thericeking** [comment]
Was this change applied to the master?
