### ISSUE TITLE
Ethash supported?

### ISSUE THREAD

**Issue by thericeking** [nemosminer/NemosMiner-v2.3#167]
@nemosminer I see Ethash listed here https://github.com/nemosminer/NemosMiner-v2.3/blob/master/Algorithms.txt

1. Is it safe to download the master and start using it? 

I like this miner better than MPM until I saw someone post requesting support for Ethash. I didn't realize this miner didn't support it until he mentioned it. 

2. Is every single algo listed on that txt supported by this miner or some are still work in progress.?

I am anxiously waiting for a new release that supports every single coin in MPH.

Thanks

**Comment by Teqqles** [comment]
I'm currently using 2.3c which doesn't yet support Ethash and the algorithm is listed in Algorithms.txt.  If the author can give us some idea of why support isn't yet available maybe the community can provide some help.  I am expecting to bring another miner online tomorrow and I have to say I'd rather be using Nemos.

**Comment by thericeking** [comment]
@Teqqles @nemosminer Closed and ignored. I guess I'll be taking my mining operation somewhere else.
