### ISSUE TITLE
% profitability switch option

### ISSUE THREAD

**Issue by Dobromir-Atanasov** [nemosminer/NemosMiner-v2.3#168]
Hello,

Is there a way to add % profitability switch option? The idea is when profitability gap between top algos is very tiny and they can change places on every api update but the difference is like 0,5 or 1 or even 2-3%, the miner had to stay at the current algo to avoid miner restart, loosing of some hashrate (for example some algos need time to catch full power) or even rig restart (if it is set close to its limits in voltage and clock).

**Comment by mullen1200** [comment]
This would be a great money making feature. I'd love to see support for this added.
