### ISSUE TITLE
Benchmarking Taking Extra Runs Per Algorithm

### ISSUE THREAD

**Issue by nobitacu** [nemosminer/NemosMiner-v2.3#176]
Hello,

Testing lasted master build. I’ve noticed on both rigs that during benchmarking, it would at times not switch to next algorithm upon switch interval (900 for me), and will once again continue to benchmark the same algorithm. Sometimes this does it once, but have seen it go on for up to 1 hour (when it was supposed to switch after 15 min, as you can see with lbry below). Thanks. 

Edit: Xevan also benched for 1 hour before switching.

Edit 2: After looking through the switch, it actually takes 2 turns for each algorithm instead of 1, and even though it said on top it's been active for 1 hour, in reality, it is actually 30 min (as I have it set at 900 interval), so the reported active time shown is double of its actual value.

Edit 3: Confirmed this also happens during regular mining session after benchmarking is complete. So in order to get the right interval I want, I need to cut seconds by half.

Thank you as always!

Below is log of current benchmarking taking place:

Idle:  1

    Speed Exited   Active   Cnt  Command
    ----- ------   ------   ---  -------
2.36 GH/s 00:00:00 00:01:00 Once Bin\NVIDIA-TPruvot\ccminer.exe -a lbry -o
                                 stratum+tcp://lbry.mine.ahashpool.com:3334 -u
                                 (address deleted for public post) -p
                                 ID=Miner,c=BTC -d 0,1,2,3,4,5,6,7,8,9
                                 --api-remote

1BTC =  13597.38 USD

   Type: NVIDIA

Miner                Algorithm        Speed     mBTC/Day      BTC/Day Bias   USD/Day
-----                ---------        -----     --------      ------- ----   -------
ccminerAlexis78      Nist5      386.61 MH/s        5.656      0.00566 5.656   76.908
CcminerTpruvot       Lbry         2.36 GH/s        2.102      0.00210 2.102   28.580
CcminerAlexis78cuda9 Xevan     Benchmarking Benchmarking Benchmarking       ...rking
CcminerTpruvotcuda9  Phi       Benchmarking Benchmarking Benchmarking       ...rking
Palgin               NeoScrypt Benchmarking Benchmarking Benchmarking       ...rking
ccminerAlexis78      Hsr       Benchmarking Benchmarking Benchmarking       ...rking
ccminerAlexis78      C11       Benchmarking Benchmarking Benchmarking       ...rking
ccminerAlexis78      X17       Benchmarking Benchmarking Benchmarking       ...rking
ccminerAlexis78      Lyra2RE2  Benchmarking Benchmarking Benchmarking       ...rking

Running:

    Speed Started  Active   Cnt  Command
    ----- -------  ------   ---  -------
0.00 PH/s 00:00:00 00:00:00 Once Bin\NVIDIA-Alexis78cuda9\ccminer_x86.exe -a xevan
                                 -o stratum+tcp://xevan.mine.ahashpool.com:3739 -u
                                 (deleted for public post) -p
                                 ID=Miner,c=BTC -d 0,1,2,3,4,5,6,7,8,9
                                 --api-remote

--------------------------------------------------------------------------------
Last Refresh: 01/15/2018 05:38:22
Sleep 900 sec
--------------------------------------------------------------------------------
Running:

    Speed Started  Active   Cnt  Command
    ----- -------  ------   ---  -------
0.00 PH/s 00:00:15 00:00:15 Once Bin\NVIDIA-Alexis78cuda9\ccminer_x86.exe -a xevan
                                 -o stratum+tcp://xevan.mine.ahashpool.com:3739 -u
                                 (deleted for public post) -p
                                 ID=Miner,c=BTC -d 0,1,2,3,4,5,6,7,8,9
                                 --api-remote

--------------------------------------------------------------------------------
Last Refresh: 01/15/2018 05:53:22
Sleep 900 sec

**Comment by nemosminer** [comment]
12mins per algo 1st benchmark

**Comment by nobitacu** [comment]
Pretty sure it was 30 min per benchmark per algorithm, I sat there and watched. Oh well, back to last version.

**Comment by nobitacu** [comment]
Whatever seconds I put into the interval, it doubles the time.
