### ISSUE TITLE
NeoScrypt is mining to your wallet instead of ours

### ISSUE THREAD

**Issue by luxferro** [nemosminer/NemosMiner-v2.3#179]
For both ccminer-alexis and palgin.

See photo (masked out my wallet address):
![nemobug2](https://user-images.githubusercontent.com/7016431/34968459-673b2176-fa37-11e7-9046-a752cf7adbd0.png)

**Comment by nemosminer** [comment]
did you edit startnicehash.bat and change my address to yours?

**Comment by nemosminer** [comment]
edit: startnicehash.bat

1.change BTC address to yours

2.select how many gpu's you have eg: (1gpu dstm 0 cc 0) (2gpu dstm 0 1 cc 0,1) (6gpu dstm 0 1 2 3 4 5 cc 0,1,2,3,4,5)

3.remove any algos you do not want to mine

4.there is a 5minute per day fee, that can be disabled by changing -Donate 5 to 0

5.run start.bat

If you have Windows 7, 8, or 8.1, please update PowerShell: https://www.microsoft.com/en-us/download/details.aspx?id=50395

CCMiner may need 'MSVCR120.dll' if you don't already have it: https://www.microsoft.com/en-gb/download/details.aspx?id=40784

CCMiner may need 'VCRUNTIME140.DLL' if you don't already have it: https://www.microsoft.com/en-us/download/details.aspx?id=48145

running multiple cards its recommended to increase Virtual Memory 64gb is optimal

Requires nvidia driver newer than 388

**Comment by luxferro** [comment]
Yeah, I did all that. You'll see that a few alogs listed mined to my wallet (whited out), but the others mined to your wallet.

**Comment by nemosminer** [comment]
im running startnicehash.bat through a full benchmark now with a different btc address in my startnicehash.bat  

to try and replicate this "new bug"

**Comment by nemosminer** [comment]
before benchmark: https://imgur.com/a/Tjujz

**Comment by luxferro** [comment]
@nemosminer hmm, i just looked, and I had thought I changed it to 0, but had set it to 50. Could that be why? 

It benched to your wallet for a couple alogs, and then when it was done benching, it switched to another alog, which was also mining to your address.

**Comment by nemosminer** [comment]
yip

**Comment by luxferro** [comment]
Okay, sorry about false alarm. I had a couple other issues though. But I'll see if they happen to others first :)

**Comment by luxferro** [comment]
Post is gone, Sorry about that.

**Comment by nemosminer** [comment]
all good thanks for your help
