### ISSUE TITLE
EWBF miner gives better results than DSTM

### ISSUE THREAD

**Issue by tr1l3r** [nemosminer/NemosMiner-v2.3#180]
Hi Nemo. Love your work and everything you have done with the miner. I've been using DSTM miner and even thou it gives better Sols than EWBF, EWBF seems to mine better from hashrates I've seen on pools and also read a bunch of articles on the net claiming the exact same thing. Can you inspect that and if it true, can you please bring back EWBF to replace DSTM? When can we expect support for ETH and ETH dual mining. Thanx for your response.

**Comment by nemosminer** [comment]
DSTM is quite a bit faster... than EWBF.....

yes claymore is planed to be added soon

**Comment by altagir** [comment]
i found DSTM is a bit higher, but i have less income than EWFB
there is also a magic option with EWFB :  --fee 0, for 0 dev fee
