### ISSUE TITLE
cannot connect to pool

### ISSUE THREAD

**Issue by mr-oli** [nemosminer/NemosMiner-v2.3#181]
Hello

I got problem with nemosminer and ahashpool

it cannot connect to pool with -region europe or -region eu, only -region us is working (but i am in europe Smiley)

Any ideas how to solve it?

I am using 2.3c beta
> Loading pool stats..
>Error contacting pool, retrying..

Is there any way to add the same algo for different pools?
For example neoscrypt for nicehash and multipoolhub?

**Comment by nemosminer** [comment]
its because ahashpool only has one server....  you can not connect to a server which does not exist

no not yet, im working on adding a startallpools.bat atm which can run 1 or more pools at once and choose which is the most profitable..

but is not completed yet.

Best Regards
Nemo
