### ISSUE TITLE
lyra2z update ccminer to djm34 code 

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.3#66]
https://github.com/djm34/ccminer-msvc2015/releases/download/v0.2.1/ccminer_cuda9.exe

**Comment by UselessGuru** [comment]
This miner gives quite a lot (approx . 5-10%) of invalid shared on MiningPoolHub.
Ccminer 2.2.2 is not quite as fast, but does not send invalid shares and it ends up being faster for me (1x GTX 1080ti, 1x GTX 10603g).

**Comment by UselessGuru** [comment]
BTW this is an aknowledged problem:
[https://github.com/djm34/ccminer-msvc2015/issues/23](url)

**Comment by nemosminer** [comment]
thanks i'll stick with 2.2.2 then

**Comment by coreshift** [comment]
I've been using this for a while now on MPH and have zero invalid shares using my OC'd gtx1080s. Works great and XZC is the most profitable coin I can mine now. Maybe something changed on MPH?

**Comment by nemosminer** [comment]
do some testing would like to just use tpruvot new 2.2.3 if possible

**Comment by coreshift** [comment]
My 2 GTX 1080's are getting 4.64 MH/s using djm34 and Tpruvot 2.2.3 x64 gives 4.55 MH/s. Both with -i 21. Only about a 2% difference.

**Comment by UselessGuru** [comment]
@coreshift 

> EDIT: No invalid shares.

Where id you check? The miner itself does not report invalid shares, but if I check on the pool I get lots :-(

**Comment by nemosminer** [comment]
i'll use 2.2.2 x64 -i 21
