### ISSUE TITLE
blake2s on ahashpool24hr reporting wrong price

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.3#83]
blake2s on ahashpool24hr reporting wrong price

: single 1070 test rig say i will make $7400 a day....

needs bug fix to ahashpool24hr.ps1

**Comment by UselessGuru** [comment]
Fixed in https://github.com/nemosminer/NemosMiner-v2.2.2/commit/1155cc2cc512d420731290084602d83ca09e6169#diff-283176e6feb211f8532b2c7c9263cd08
