### ISSUE TITLE
NemosMiner-v2.3-beta (PLEASE POST v.2.3-beta Issues here)

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.3#87]

**Comment by mahpoul22** [comment]
@nemosminer Where can I find a link for the 2.3 pls?

**Comment by mahpoul22** [comment]
Got this right now

Windows PowerShell transcript start
Start time: 20171215212207
Username: 
RunAs User: 
Machine:  (Microsoft Windows NT 10.0.15063.0)
Host Application: powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle minimized -command &.\NemosMiner-v2.3.ps1 -SelGPUEWBF '0' -SelGPUCC '0' -Currency EUR -Passwordcurrency BTC -interval 120 -Username Mahpoul22 -Workername GPU -Location EU -PoolName miningpoolhub -Type nvidia -Algorithm cryptonight,lyra2z,skein,equihash,groestl,MyriadGroestl,Lyra2RE2,neoscrypt -Donate 0
Process ID: 520
PSVersion: 5.1.15063.786
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.15063.786
BuildVersion: 10.0.15063.786
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1

Transcript started, output file is .\Logs\2017-12-15_21-22-07.txt
Loading BTC rate from 'api.coinbase.com'..
Loading pool stats..
PS>TerminatingError(Invoke-WebRequest): "The remote server returned an error: (522) Origin Connection Time-out."
Error contacting pool, retrying..

**Comment by nemosminer** [comment]
not sure just ran MPH.bat myself to test all is well runs right through and completes benchmark then starts mining most profitable algo...

those logs aren't really showing me anything can you send me a screen shot of the NemosMiner window  please

**Comment by mahpoul22** [comment]
Here you are 

![nm_2 3](https://user-images.githubusercontent.com/8970762/34059714-67baac12-e1e0-11e7-81a5-e451bf418a91.PNG)

**Comment by nemosminer** [comment]
thanks yeh its telling you what is wrong it cant contact pool...
im not sure why you can't... i can contact pool on my rigs you may want to check your firewall/AV see if something is blocking it? have you tried a different pool to see if it works?

**Comment by mahpoul22** [comment]
Tried differents pool same issue, tried without windows defender, same issue.

**Comment by mrcs64** [comment]
I've had similar issue with connectiong, but when miner was already working. Had it running for ~5h and was stuck on loading BTC rate.

**Comment by yepla** [comment]
It's now 20 minutes than the benchmarking on MyriadGroestl is running and still not finished
when the tool switch to an other algo there are an error write in red speaking of pid missing

**Comment by nemosminer** [comment]
@yepla MyriadGroestl ? which pool can you said me a screen shot of error please

**Comment by yepla** [comment]
i don t have a screen shot i have switch back on the version before but when i have stop the miner it was more than 30min in benchmarking on mining pool hub on MyriadGroestl

**Comment by nemosminer** [comment]
@yepla thanks

**Comment by jayntguru** [comment]
The summary at the bottom goes away.

Usually like this:

MultiPoolMiner is between 0% and 5% more profitable than the fastest miner:

Miner                         BTC                              USD
-----                         ---                              ---
MultiPoolMiner                0.00020 ±100 % (0.00010-0.00039) 3.72447 ±100 % (1.86223-7.44894)
ClaymoreAmdLbry40-Ethash/Lbry 0.00019 ±2 % (0.00019-0.00019)   3.63336 ±2 % (3.57817-3.68941)

Now like this:

Miner             Pool          Algorithm Watchdog Timer
-----             ----          --------- --------------
Sgminer           Hashrefinery  Lyra2RE2   1,488 Seconds
ClaymoreAmdLbry40 MiningPoolHub Ethash         0 Seconds
ClaymoreAmdLbry40 AHashPool     Lbry           0 Seconds

**Comment by yepla** [comment]
something wrong with the miner cryptonight x64 the miner seems not start or start and close directly (v2.3a-beta) :(

**Comment by Olegik-ah** [comment]
Minor bug. When NemosMiner changes algo - i see the error. This is only error message - all works as expected (old miner closes, new miner starts).
![_minor_bug](https://user-images.githubusercontent.com/31293967/34125594-cb84a8ba-e447-11e7-8110-32546a2c86e3.png)

**Comment by nemosminer** [comment]
fixed
