### ISSUE TITLE
linux version

### ISSUE THREAD

**Issue by yepla** [nemosminer/NemosMiner-v2.3#88]
Hello,

It will be great to make a linux version if it s possible.

Thanks.

**Comment by jagauthier** [comment]
Powershell doesn't run on Linux.  It would be a completely different application. Although Python would be a moderate suggestion for cross platform.

**Comment by yepla** [comment]
@jagauthier yes i know but a linux version will be great on linux you not need something on card to enable the gpu and u mine quick than on windows especially for ethash !

**Comment by nemosminer** [comment]
its coming

**Comment by yepla** [comment]
@nemosminer cool !!! good news !!!

**Comment by OrlandoF** [comment]
PowerShell os multiplataforma for a white nos.
https://github.com/PowerShell/PowerShell/blob/master/docs/learning-powershell/README.md

**Comment by jagauthier** [comment]
I wasn't aware. nice!

**Comment by dseeker** [comment]
Let us know if u need testing, can't wait to try it :D
