### ISSUE TITLE
getting this error... loading pool stats error

### ISSUE THREAD

**Issue by StartxPH** [nemosminer/NemosMiner-v2.3#89]
Transcript started, output file is .\Logs\2017-12-17_11-44-06.txt
Loading BTC rate from 'api.coinbase.com'..
Loading pool stats..
PS>TerminatingError(Invoke-WebRequest): "The remote server returned an error: (522) Origin Connection Time-out."
Error contacting pool, retrying..
Loading BTC rate from 'api.coinbase.com'..
Loading pool stats..

**Comment by mahpoul22** [comment]
@StartxPH  I use to have this issue and I fixed it not a long ago.

What does your start.bat look like?

**Comment by StartxPH** [comment]
i only change the addresss and the amount of gpu ... nothing else

**Comment by mahpoul22** [comment]
Show me the content of startminingpoolhub.bat

**Comment by Weeeishy** [comment]
I updated from 2.2.2 which was working fine to the latest commit and this error started to show up.

startzpool24hr.bat
`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\NemosMiner-v2.3.ps1 -SelGPUEWBF '0' -SelGPUCC '0' -Currency USD -Passwordcurrency BTC -interval 120 -Wallet 1K8gLW2amFsf9K6xbPqsns2p6tgMG1woWX -Location US -PoolName zpool24hr -Type nvidia -Algorithm poly,hsr,phi,keccak,xevan,veltor,lyra2z,skunk,tribus,c11,x11evo,lbry,skein,equihash,groestl,timetravel,sib,bitcore,x17,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,blake2s -Donate 5`

**Comment by nemosminer** [comment]
@Weeeishy 2.3a-beta will be out today addressing this issue

**Comment by krzysztof-hellostudio** [comment]
also getting the error contacting pool, retrying error. on latest v2.3a-beta

**Comment by nemosminer** [comment]
@krzysztof-hellostudio v2.3b-beta will be out today addressing this issue

**Comment by mahpoul22** [comment]
@krzysztof-hellostudio What server are you using? US, EU? If using EU type europe instead of EU.

**Comment by krzysztof-hellostudio** [comment]
@mahpoul22 yep. using EU, latest version with "Europe" works fine indeed

**Comment by prodigy18** [comment]
can somebody help me
I am constantly getting this error when i run startminingpoolhub.bat file --

Loading BTC rate from 'api.coinbase.com'..
Loading pool stats..
Error contacting pool, retrying..

**Comment by SuperJT** [comment]
I see this issue on the 2.4.1 consistently, but eventually it will work.
Looking at the packet capture, it appears that zpool is not responding with anything when reaching out to zpool.ca/api/status

I confirm this by browsing to the http site, and it very clearly returns nothing.  At least in my case it appears to be an issue with zpool.  I wonder if there is a throttle for the number of api requests per minute.  As I have other rigs and it is also seen on them.

**Comment by lunatis** [comment]
SuperJT... im having the exact same issue with the 24hr... normal zpool just works with no issues, but i rather use 24hr :(

**Comment by cryptoworld9016** [comment]
@prodigy18 did u find any solution to the error???.....i am facing the same issue ...not able to find any solutions ....
![whatsapp image 2018-01-30 at 12 45 34 am](https://user-images.githubusercontent.com/35606194/35564076-f2c2ff68-05de-11e8-8072-f2bb9de3fc1d.jpeg)

**Comment by lunatis** [comment]
i havent mate... i wanted to use the bloody zpoll24hr and it fails all the
time... so sad... ahashpool is failing hard... if i go and check my earning
graphics, has been showing like a straight line for the last 2 days, and i
can see on the miners that they are mining as normal... really pissing me
off. ill let you know if I find something.. please let me know if you find
it as well...

cheers

**Comment by cryptoworld9016** [comment]
For the time being i am using Awesome miner for zpool and mining pool hub .....its hard to know which one give more profit so i am testing it now .....ill run Awesome miner for Zpool for 24hrs and then same think for minipool hub ....will upload the results as soon as i am done......Wanted to use the Default miner of zpool but thats not happening i guess...
