### ISSUE TITLE
Why price is so high ? 

### ISSUE THREAD

**Issue by StartxPH** [nemosminer/NemosMiner-v2.3#91]
CcminerAlexis78cuda9 Keccak          2.68 GH/s 0.10125 1,884.780    0.03775 zpool-

something is wrong... i tried 2 pc using 2.2.2

**Comment by UselessGuru** [comment]
Zpool has changed its config, thats why keccak reports earnings 1000 times to high.
Download the latest Zpool pool files.

**Comment by StartxPH** [comment]
got it working a while ago...
