### ISSUE TITLE
Pls, add dstm's ZCash Cuda miner

### ISSUE THREAD

**Issue by Olegik-ah** [nemosminer/NemosMiner-v2.3#93]
https://bitcointalk.org/index.php?topic=2021765.0
5-10% faster than ewbf...

**Comment by nemosminer** [comment]
sure

**Comment by Olegik-ah** [comment]
I'm programmer. But i have never used powershell before and it's very difficult to me to understand syntax.
There is some code for dstm
[https://github.com/aaronsace/MultiPoolMiner/blob/master/APIs/Dstm.ps1](url)
[https://github.com/aaronsace/MultiPoolMiner/blob/master/Miners/Dstm.txt](url)

**Comment by nemosminer** [comment]
https://github.com/nemosminer/NemosMiner-v2.3/archive/2.3b-+-dstm.zip

need help i have it downloading running and bench marking 

but it will not close and report hash-rate after it 2 minute -interval 

any help testing and correcting problem will be much appreciated

**Comment by Olegik-ah** [comment]
Hello! Where is modded include.ps1?
You need modified function "Get-HashRate" for processing DSTM api...
https://github.com/aaronsace/MultiPoolMiner/blob/master/APIs/Dstm.ps1
this is working code, but i dont know powershell syntax to convert it in function "Get-HashRate"

**Comment by UselessGuru** [comment]
I will provide a modified include.ps1 tonight.

**Comment by nemosminer** [comment]
@UselessGuru  Thankyou very much appreciated your the man

**Comment by nemosminer** [comment]
@Olegik-ah  Done
