### ISSUE TITLE
NemosMiner-v2.3b-beta (PLEASE POST v.2.3b-beta Issues here)

### ISSUE THREAD

**Issue by nemosminer** [nemosminer/NemosMiner-v2.3#95]

**Comment by jjude80** [comment]
Error contacting pool, retrying..
bat file
`powershell -version 5.0 -noexit -executionpolicy bypass -windowstyle maximized -command "&.\NemosMiner-v2.3.ps1 -SelGPUDSTM '0 1' -SelGPUCC '0,1' -Currency USD -Passwordcurrency TZC -interval 600 -Wallet TnQKPW4FCXksBFMLMgYE7eq3eFVNfBBc6j -Location US -PoolName zpool24hr -WorkerName ID=NemosMiner-v2.3 -Type nvidia -Algorithm poly,hsr,phi,keccak,xevan,veltor,skunk,tribus,c11,x11evo,lbry,skein,equihash,groestl,timetravel,sib,bitcore,x17,blakecoin,Nist5,MyriadGroestl,Lyra2RE2,neoscrypt,blake2s,x11 -Donate 5`

**Comment by yepla** [comment]
I have try the v2.3b but after starting it when it s launch the benchmarking and when is mining Feathercoin (neoscript) on miningpoolhub the benchmarking not stop it still mining the same coin after more than 30min :(
So i go back on the version 2.2.2 ... :(
