### ISSUE TITLE
Switching coins too often

### ISSUE THREAD

**Issue by aldasa** [nemosminer/NemosMiner-v2.3#96]
MiningPoolHub pools are PPLNS which penalizes pool hoppers. 

It there a way to slow down coin switching so it stays on the same coin longer (6+) hours or so?

Or can I set it to only check for best coin to mine once every 6 hours?

Thanks.

**Comment by Olegik-ah** [comment]
Hello! In bat file param -interval 120
120 - refresh/recheck interval in seconds. If you want 6 hours = 6*60*60 = 21600
Set  -interval 21600 in your bat file

**Comment by aldasa** [comment]
Awesome, Ty.
